 export const players = [
        {
          playerId: 1,
          playerName: "Patrick Mahomes",
          price: "45",
          team: "KC",
          joiningDate: "04/27/2017",
        },
        {
          playerId: 2,
          playerName: "Tom Brady",
          price: "30",
          team: "TB",
          joiningDate: "04/16/2020",
        },
        {
          playerId: 3,
          playerName: "Aaron Rodgers",
          price: "37",
          team: "NYJ",
          joiningDate: "04/26/2023",
        },
        {
          playerId: 4,
          playerName: "Josh Allen",
          price: "43",
          team: "BUF",
          joiningDate: "04/26/2018",
        },
        {
          playerId: 5,
          playerName: "Joe Burrow",
          price: "46",
          team: "CIN",
          joiningDate: "07/31/2020",
        },
        {
          playerId: 6,
          playerName: "Dak Prescott",
          price: "40",
          team: "DAL",
          joiningDate: "04/30/2016",
        },
        {
          playerId: 7,
          playerName: "Jalen Hurts",
          price: "44",
          team: "PHI",
          joiningDate: "04/24/2020",
        },
        {
          playerId: 8,
          playerName: "Lamar Jackson",
          price: "42",
          team: "BAL",
          joiningDate: "06/05/2018",
        },
        {
          playerId: 9,
          playerName: "Christian McCaffrey",
          price: "38",
          team: "SF",
          joiningDate: "10/20/2022",
        },
        {
          playerId: 10,
          playerName: "Travis Kelce",
          price: "34",
          team: "KC",
          joiningDate: "06/06/2013",
        },
        {
          playerId: 11,
          playerName: "Tua Tagovailoa",
          price: "36",
          team: "MIA",
          joiningDate: "04/23/2020",
        },
        {
          playerId: 12,
          playerName: "Justin Herbert",
          price: "41",
          team: "LAC",
          joiningDate: "04/23/2020",
        },
        {
          playerId: 13,
          playerName: "Matthew Stafford",
          price: "35",
          team: "LAR",
          joiningDate: "03/18/2021",
        },
        {
          playerId: 14,
          playerName: "Kirk Cousins",
          price: "33",
          team: "ATL",
          joiningDate: "03/13/2024",
        },
        {
          playerId: 15,
          playerName: "Trevor Lawrence",
          price: "39",
          team: "JAX",
          joiningDate: "04/29/2021",
        },
        {
          playerId: 16,
          playerName: "Brock Purdy",
          price: "28",
          team: "SF",
          joiningDate: "04/30/2022",
        },
        {
          playerId: 17,
          playerName: "Russell Wilson",
          price: "31",
          team: "PIT",
          joiningDate: "03/15/2024",
        },
        {
          playerId: 18,
          playerName: "Derrick Henry",
          price: "32",
          team: "BAL",
          joiningDate: "03/13/2024",
        },
        {
          playerId: 19,
          playerName: "Tyreek Hill",
          price: "29",
          team: "MIA",
          joiningDate: "03/23/2022",
        },
        {
          playerId: 20,
          playerName: "Stefon Diggs",
          price: "30",
          team: "HOU",
          joiningDate: "04/03/2024",
        },
      ];